<?php
$price = $block->getProductPrize();
$collection = $block->getCollection();
$bank = $block->getOnlyBank();
$emiLeastAmt = [];
// print_r($block->getJsonData());
?>
<div id="emi"></div>

<div id="popup-modal">
    <h3> EMI details of banks</h3>

    <div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
        <?php foreach ($bank as $data) :
            $bankname = $data['bank_name']; ?>
            <button class="accordion" data-role="collapsible">
                <div data-role="trigger">
                    <span><?php echo $bankname; ?></span>
                </div>
            </button>
            <div class="panel" data-role="content">
                <table class="data table" id="test-data-table">
                    <thead>
                        <tr>
                            <th scope="col" class="col content">EMI Plan</th>
                            <th scope="col" class="col content">EMI Amount</th>
                            <th scope="col" class="col created_at">Interest(pa)</th>
                            <th scope="col" class="col actions">Price</th>
                            <th scope="col" class="col actions">Total Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $bankdetails = $block->getBankDetails($bankname);
                        foreach ($bankdetails as $bankdesc) :
                            $emi = $block->emiCalculation($price, $bankdesc['roi'], $bankdesc['month']);
                            array_push($emiLeastAmt, $emi[0]);
                        ?>
                            <tr>
                                <td data-th="Emi" class="col emi"><?php echo $bankdesc->getMonth() . "m" . " @ " . $bankdesc->getBankRoi() . "% pa"; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . round($emi[0]) . "/month"; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . ceil($emi[1]) . " (" . $bankdesc->getBankRoi() . "%)"; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . $price; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . ceil($emi[2]); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php endforeach; ?>
    </div>
    <?php $leastEmiValue = min($emiLeastAmt); ?>
</div>

<?php
if ($block->toShowBlock()) : ?>
    <span>EMI starts from <?php echo "$" . round($leastEmiValue); ?>/month. Standards EMI also available <a href="#" id="click-me">View plans</a></span>
<?php endif; ?>

<script>
     require(
        [
            'jquery'
        ],
        function (
            $
        ) {
            $('body').on('click', '#click-me', function () {
 
                // var self = $(this);
                var url = "<?php echo $block->getUrl() . 'emicalc/Index/Test' ?>";
                console.log(url);
                try {
 
                    $.ajax({
                        url: url,
                        type: 'POST',
                        dataType: 'json',
                        showLoader: true,
                        success: function (data) {
                            // console.log(json_decode(data));
                            $("#emi").html(data);
                            
                        }
                    });
                } catch (e) {
                }
 
            });
        });
</script>