 <?php
   $blockObj= $block->getLayout()->createBlock('Ambab\EMImodule\Block\Catalog\Product\View');
   $bank = $blockObj->getOnlyBank();
   $price = $blockObj->getTotal();
   $isEnable = $blockObj->toShowBlock();
?>

<div id="popup" style="display: none;">
   <div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
        <?php foreach ($bank as $data) :
            $bankname = $data['bank_name']; ?><br>
            <button class="accordion" data-role="collapsible">
                <div data-role="trigger">
                    <span><?php echo $bankname; ?></span>
                </div>
            </button>
            <div data-role="content" class="collapsibleContent">
                <table class="data table" id="test-data-table">
                    <thead>
                        <tr>
                            <th scope="col" class="col content">EMI Plan</th>
                            <th scope="col" class="col content">EMI Amount</th>
                            <th scope="col" class="col created_at">Interest(pa)</th>
                            <th scope="col" class="col actions">Price</th>
                            <th scope="col" class="col actions">Total Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $bankdetails = $blockObj->getBankDetails($bankname);
                        foreach ($bankdetails as $bankdesc) :
                            $emi = $blockObj->emiCalculation($price, $bankdesc['roi'], $bankdesc['month']);
                        ?>
                            <tr>
                                <td data-th="Emi" class="col emi"><?php echo $bankdesc['month'] . "m"." @ ". $bankdesc['roi']. "% pa"; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . round($emi[0]) . "/month"; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . ceil($emi[1]) . " (" . $bankdesc['roi'] . "%)"; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . $price; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . ceil($emi[2]); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php endforeach; ?>
   </div>
</div>

<script>
    var isEmiEnable = <?php echo json_encode($isEnable)?>
</script>