 <?php
   $blockObj= $block->getLayout()->createBlock('Ambab\EMImodule\Block\Catalog\Product\View');
   $bank = $blockObj->getOnlyBank();
   $price = $blockObj->getSubtotal();
?>

<div id="popup" style="display: none;">
   <div id="element" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
        <?php foreach ($bank as $data) :
            $bankname = $data['bank_name']; ?><br>
            <button class="accordion" data-role="collapsible">
                <div data-role="trigger">
                    <span><?php echo $bankname; ?></span>
                </div>
            </button>
            <div data-role="content" class="collapsibleContent">
                <table class="data table" id="test-data-table">
                    <thead>
                        <tr>
                            <th scope="col" class="col content">EMI Plan</th>
                            <th scope="col" class="col content">EMI Amount</th>
                            <th scope="col" class="col created_at">Interest(pa)</th>
                            <th scope="col" class="col actions">Price</th>
                            <th scope="col" class="col actions">Total Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $bankdetails = $blockObj->getBankDetails($bankname);
                        foreach ($bankdetails as $bankdesc) :
                            $month = $bankdesc['month'];
                            $roi = $bankdesc['roi'];
                            $r = $roi / (12 * 100);
                            $emi = $blockObj->emiCalculation($price, $r, $month);
                            $interestamt = ($emi * $month) - $price;
                            $totalPrice = $price + $interestamt;
                        ?>
                            <tr>
                                <td data-th="Emi" class="col emi"><?php echo $bankdesc['month'] . "m"." @ ". $bankdesc['roi']. "% pa"; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . round($emi) . "/month"; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . ceil($interestamt) . " (" . $bankdesc['roi'] . "%)"; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . $price; ?></td>
                                <td data-th="Emi" class="col emi"><?php echo "$" . ceil($totalPrice); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php endforeach; ?>
   </div>
</div>