<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\TestFramework\Utility\ChildrenClassesSearch\E;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$qtyBlock= $block->getLayout()->createBlock('Ambab\EMImodule\Block\Catalog\Product\Price');
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_product = $block->getProduct();

// Stock qty 
$sku = $_product->getSku();
if ($_product->getTypeId() == 'simple'){
    $qty = $qtyBlock->getProductSalableQty($sku);
}

if (!$_product instanceof \Magento\Catalog\Model\Product) {
    return;
}

$_call = $block->getAtCall();
$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();

$renderLabel = true;
// if defined as 'none' in layout, do not render
if ($_attributeLabel == 'none') {
    $renderLabel = false;
}

if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code))
        ? $_product->getAttributeText($_code)
        : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php if ($_attributeValue) :?>
<div class="product attribute <?= $block->escapeHtmlAttr($_className) ?>">
    <?php if ($renderLabel) :?>
        <strong class="type"><?= $block->escapeHtml($_attributeLabel) ?></strong>
    <?php endif; ?>

    <div class="value" <?= /* @noEscape */ $_attributeAddAttribute ?>><?= /* @noEscape */ $_attributeValue ?></div><br>
    
    <!-- Showing Stock qty -->
    <strong>
        <?php if(isset($qty)) :?>
            <span style="font-size: 20px;"><?= $qty ?></span>
            <span> Units left</span>
        <?php endif;?>
    </strong><br>

    <!-- Adding Icon on product details page -->
    <?php if ($_product->getHot()) : ?>
        <span class="hot-icon">HOT</span>
    <?php endif; ?> 
</div>
<?php endif; ?>


